spring:
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        default_schema: <default_schema_name>
  datasource:
    url: jdbc:postgresql://<host>:<port>/<dbName>
    username: <username>
    password: <password>

